; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Leave Cut-Off Service"
#define MyAppVersion "1.0"
#define MyAppPublisher "NBC (Philippines) Car Technology Corporation"
#define MyAppExeName "CutOffService.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0CE9FC80-691B-4EB4-AD1C-BEABCCE0F0E1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\Leave Application
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=B:\Users BACKUP\NBCP-LT-058\Documents\Visual Studio 2012\Projects\LeaveFilingSystem\CutOffService\inno
OutputBaseFilename=cutoff-serv-inst
SetupIconFile=B:\Users BACKUP\NBCP-LT-058\Documents\Visual Studio 2012\Projects\LeaveFilingSystem\CutOffService\Resources\LfsSysIcon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "B:\Users BACKUP\NBCP-LT-058\Documents\Visual Studio 2012\Projects\LeaveFilingSystem\CutOffService\bin\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "B:\Users BACKUP\NBCP-LT-058\Documents\Visual Studio 2012\Projects\LeaveFilingSystem\CutOffService\bin\Debug\BlackCoffeeLibrary.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

